2019-03-08 17:38:51,476 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
2019-03-20 11:22:47,384 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
2019-03-20 11:22:59,587 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
2019-03-20 13:20:13,979 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
2019-03-20 13:20:21,587 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
2019-03-20 13:27:37,600 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
2019-03-20 13:32:27,911 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
2019-03-20 14:02:45,806 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
2019-03-20 14:19:05,930 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
2019-03-20 14:19:28,978 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
2019-03-20 14:20:31,647 ERROR: Exception on /follow/cmcavinue [GET] [in c:\inetpub\wwwroot\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\inetpub\wwwroot\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\inetpub\wwwroot\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\inetpub\wwwroot\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\inetpub\wwwroot\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\inetpub\wwwroot\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\inetpub\wwwroot\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\inetpub\wwwroot\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\inetpub\wwwroot\microblog\app\routes.py", line 110, in follow
    db.commit.session()
AttributeError: 'SQLAlchemy' object has no attribute 'commit'
2019-03-20 14:21:22,056 INFO: Microblog startup [in C:\inetpub\wwwroot\microblog\app\__init__.py:43]
